# Generated by Django 4.2.1 on 2023-05-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_rename_title_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases_num',
            field=models.IntegerField(default=0),
        ),
    ]
