# Generated by Django 4.2.1 on 2023-06-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0008_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
    ]
