# Generated by Django 4.2.1 on 2023-06-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0004_alter_basketproduct_product'),
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_basket.basket'),
        ),
    ]
