# Generated by Django 4.2.1 on 2023-06-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0004_alter_basketproduct_product'),
        ('app_order', '0007_alter_order_basket_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_basket.basket'),
        ),
    ]
