# Generated by Django 4.2.1 on 2023-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0010_alter_order_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
