# Generated by Django 4.2.1 on 2023-06-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_sale'),
        ('app_basket', '0002_rename_count_basketproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='app_product.product'),
        ),
    ]
