# Generated by Django 4.2.1 on 2023-06-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0006_alter_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketproduct',
            options={'verbose_name': 'Basket product', 'verbose_name_plural': 'Basket products'},
        ),
    ]
